name: Nightly release

on:
  schedule:
    - cron: '23 23 * * *'

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/daily-version-action@v2
        id: daily-version
        with:
          prefix: v
      - name: Create release
        if: steps.daily-version.outputs.created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME" # GITHUB_REF_NAME is the tag name in `on.push.tags` workflows
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.daily-version.outputs.version }}